spring:
  datasource:
    url: jdbc:mysql://localhost:3306/world
    username: root
    password: root
    driver-class-name:com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.mistifler.demo.springbootmybatis.entity
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis.xml
